version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: apify
    versions:
    - 0.21.12
    - 1.0.0
    - 1.0.1
    - 1.0.2
    - 1.1.0
    - 1.1.1
